# Generated by Django 4.2.1 on 2025-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_management",
            "0002_order_alter_product_name_orderitemthrough_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemthrough",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitemthrough",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
